kind: pipeline
name: default

steps:
  - name: install
    image: ubuntu:18.04
    commands:
      - >
        useradd -m -s /bin/bash parham \
          && echo "parham:parham" | chpasswd && adduser parham sudo
      - apt-get update && apt-get install sudo
      - sudo -u parham /bin/bash -c 'echo $(whoami)'
      - sudo -u parham /bin/bash -c 'yes "Y" | ./start.sh env'
      - sudo -u parham /bin/bash -c 'yes "Y" | ./install.sh -y'
      - > # check symlinks
        [ $(readlink $HOME/.zshrc) = $PWD/zsh/zshrc ]
