language: c
sudo: enabled
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y zsh vim tmux
  - sudo apt-get install -y neovim
script:
  - yes "Y" | ./install.sh -m -y
  - yes "Y" | ./install.sh -y
