---
language: shell
os: linux
dist: focal

before_install:
  - ./start.sh env
  - . ~/.profile
install:
  - yes "Y" | ./install.sh -y
  # vim linter
  - pip3 install vim-vint
script:
  - vint --enable-neovim ./nvim/init.vim ./nvim/coc.vim
  - vint ./vim/vimrc
  - test $(readlink -f ~/.zshrc) = $(pwd)/zsh/zshrc
  - bash -c hash nvim
  - zsh -c hash nvim
