---
language: shell
os: linux
dist: bionic

before_install:
  - ./start.sh brew
  - ./start.sh env
install:
  - yes "Y" | ./install.sh -y
script:
  - test $(readlink -f ~/.zshrc) = $(pwd)/zsh/zshrc
  - test $(readlink -f ~/.bashrc) = $(pwd)/conf/bashrc
  - bash
  - hash brew
  - hash nvim
  - zsh
  - hash brew
  - hash nvim
