---
language: shell
os: linux
dist: bionic

before_install:
  - ./start.sh brew
  - ./start.sh env
install:
  - yes "Y" | ./install.sh -y
script:
  - [ $(readlink -f ~/.zshrc) = $(pwd)/zsh/zshrc ]
  - [ $(readlink -f ~/.bashrc) = $(pwd)/conf/bashrc ]
