icons_format = "{icon}"

[theme]
theme = "semi-native"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $barchart $utilization "
format = " $icon $frequency{ $boost|} "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"

[[block]]
block = "net"
interval = 1
device = "snapp-1"
format = " snapp-1 $ip "
missing_format = ""

[[block]]
block = "net"
interval = 1
device = "snapp-2"
format = " snapp-2 $ip "
missing_format = ""

[[block]]
block = "net"
interval = 1
device = "offerland"
format = " offerland $ip "
missing_format = ""

[[block]]
block = "net"
interval = 1
device = "connectify0"
format = " connectify0  $ip "
missing_format = "  "
