icons_format = "{icon}"

[theme]
theme = "semi-native"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $barchart $utilization "
format = " $icon $frequency{ $boost|} "
[block.theme_overrides]
idle_fg = "#FFC0CB"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
alert_unit = "GB"
interval = 20
warning = 500.0
alert = 800.0
format = " $icon root: $used.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[block.theme_overrides]
idle_fg = "#FF4040"

[[block]]
block = "sound"
[block.theme_overrides]
idle_fg = "#FFEFDB"

[[block]]
block = "net"
interval = 1
device = "snapp-1"
format = " snapp-1 $ip "
missing_format = ""
[block.theme_overrides]
idle_fg = "#A0DB8E"

[[block]]
block = "net"
interval = 1
device = "snapp-2"
format = " snapp-2 $ip "
missing_format = ""
[block.theme_overrides]
idle_fg = "#A0DB8E"

[[block]]
block = "net"
interval = 1
device = "offerland"
format = " offerland $ip "
missing_format = ""
[block.theme_overrides]
idle_fg = "#89CFF0"

[[block]]
block = "net"
interval = 1
device = "connectify0"
format = " connectify0 $ip "
missing_format = "  "
[block.theme_overrides]
idle_fg = "#F2B31C"

[[block]]
block = "custom"
command = ''' couple.sh relationship | head -1 '''
format = " 󰣐 $text.pango-str() "
interval = 3600
[block.theme_overrides]
idle_fg = "#FFB2B2"

[[block]]
block = "custom"
command = ''' couple.sh birthday | head -1 '''
format = " 󱟰 $text.pango-str() "
interval = 3600
[block.theme_overrides]
idle_fg = "#8E7CC3"
