icons_format = "{icon}"

[theme]
theme = "semi-native"

[icons]
icons = "material-nf"

[[block]]
block = "uptime"
interval = 3600  # update every hour

[[block]]
block = "load"
format = " $icon load: $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4)"
interval = 1
info = 0.3
warning = 0.6
critical = 0.9
[block.theme_overrides]
idle_fg = "#1aff58"
warning_fg = "#cccc00"
critical_fg = "#ff4500"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 1

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R %Z') "
timezone = ["Asia/Tehran", "UTC"]

[[block]]
block = "bluetooth"
mac = "AC:80:0A:45:A3:1F"
disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
full_format = " $icon ✅ "
