---
- name: packages
  become: true
  hosts: all
  tasks:
    - name: Install packages
      apt:
        update_cache: true
        pkg:
          - htop
          - atop
          - aria2
          - curl
          - tmux
          - bat
          - neovim
          - python3-pynvim
          - jq
          - yamllint
          - bmon
          - zsh
        state: latest

- name: dotfiles
  become: false
  hosts: all
  tasks:
    - name: Clone dotfiles
      git:
        repo: https://github.com/1995parham/dotfiles
        dest: $HOME/Documents/dotfiles
    - name: Install dotfiles
      ansible.builtin.shell:
        cmd: yes Y | $HOME/Documents/dotfiles/install.sh -y
