# path {{{
# prevent from duplicate records in path
typeset -U path
# }}}

# python {{{

export VIRTUALENV_SYSTEM_SITE_PACKAGES=true

# }}}

# rust {{{

if [ -d "$HOME/.cargo" ]; then
	path+=("$HOME/.cargo/bin")
fi

# }}}

# podman, helm, everything that is related to clouds. {{{

export AWS_VAULT_BACKEND=file

# }}}

# home-made paths {{{

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
	path+=("$HOME/bin")
fi

# set PATH so it includes user's local private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
	path+=("$HOME/.local/bin")
fi

# }}}

# languages {{{

# you may need to manually set your language environment
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# }}}

# editors and terminals {{{

EDITOR="$(which nvim)"
export EDITOR

SUDO_EDITOR="$(which nvim)"
export SUDO_EDITOR

TERM="xterm-256color"
export TERM

DISABLE_AUTO_TITLE='true'
export DISABLE_AUTO_TITLE

# }}}

# path {{{

export PATH

# }}}
