# PATH {{{
# prevent from duplicate records in path
typeset -U path
# }}}

# ELone {{{
source $HOME/.zsh.plug/elone.zsh
# }}}

# Oh-My-ZSH {{{

ZSH=$HOME/.oh-my-zsh

# If you come from bash you might have to change your $PATH.
path+=('/usr/local/bin')

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="1995parham"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.zsh.plug

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  golang
  pyenv
  vi-mode
  pj
  gitignore
  docker
  gnu-utils
  ng
  oc
  kubectl

  travis
  revel
  proxy
)

# Load ELone after your oh-my-zsh configuration
elone oh
elone bundle 1995parham/buffalo.zsh buffalo

source $ZSH/oh-my-zsh.sh

# local configuration
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

# }}}

# Plugin configuration {{{
# pj
PROJECT_PATHS=(~/Documents/Git/parham ~/Documents/Go/src)
# }}}

# User configuration {{{

# export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"
export TERM="xterm-256color-italic"
if [ -f $HOME/.dircolors ]; then
  eval `dircolors $HOME/.dircolors`
fi
if [ -d $HOME/bin ]; then
  path+=("$HOME/bin")
fi

if [ -d /snap/bin ]; then
  path+=('/snap/bin')
fi

# You may need to manually set your language environment
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# edit command in vim
bindkey -M vicmd v edit-command-line

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
alias grep="grep --color=auto"
alias vi="vim"
alias vim="nvim"
alias r="source ~/.zshrc"
alias tat='tmux new-session -As $(basename "$PWD" | tr . -)' # will attach if session exists, or create a new session
alias tmuxsrc="tmux source-file ~/.tmux.conf"
alias tmuxkillall="tmux ls | cut -d : -f 1 | xargs -I {} tmux kill-session -t {}" # tmux kill all sessions
alias ct="ctags -R --exclude=.git --exclude=node_modules"
alias dotfiles="ls -a | grep '^\.' | grep --invert-match '\.DS_Store\|\.$'"

# }}}

# Go {{{

export GOPATH=$HOME/Documents/Go
if [ -d $HOME/Documents/Go/bin ]; then
  path+=("$HOME/Documents/Go/bin")
fi

# }}}

# Rust {{{

if [ -d $HOME/.cargo ]; then
  path+=("$HOME/.cargo/bin")
fi

# }}}

# Github {{{

export GITHUB_USER="1995parham"
export HOMEBREW_GITHUB_API_TOKEN="0dcb9b50e36d83de6ddbcff7b448b929399fc869"

# }}}

# PATH {{{
export PATH
# }}}
