# Antigen {{{

source $HOME/.zsh.plug/antigen.zsh

unset ZSH
ZSH_CUSTOM=$HOME/.zsh.plug

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle command-not-found
antigen bundle git
antigen bundle go
antigen bundle pyenv
antigen bundle vi-mode
antigen bundle pj
antigen bundle gitignore
antigen bundle docker
antigen bundle gnu-utils

# Bundles local plugins
antigen bundle $ZSH_CUSTOM/plugins/travis
antigen bundle $ZSH_CUSTOM/plugins/govc
antigen bundle $ZSH_CUSTOM/plugins/revel

# prompt theme
antigen theme $ZSH_CUSTOM themes/1995parham

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Buffalo web framework bundle.
antigen bundle 1995parham/buffalo.zsh

# Tell antigen that you're done.
antigen apply

# }}}

# Initiation + Oh My ZSH {{{
source $ZSH/oh-my-zsh.sh

# If you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:$PATH

# local configuration
if [ -f $HOME/.zshrc.local ]; then
	source $HOME/.zshrc.local
fi

# }}}

# Plugin configuration {{{
# pj
PROJECT_PATHS=(~/Documents/Git/parham ~/Documents/Go/src)
# }}}

# User configuration {{{

# export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"
export TERM="xterm-256color-italic"
if [ -f $HOME/.dircolors ]; then
	eval `dircolors $HOME/.dircolors`
fi
if [ -d $HOME/bin ]; then
	PATH="$PATH:$HOME/bin"
fi

# You may need to manually set your language environment
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# edit command in vim
bindkey -M vicmd v edit-command-line

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
alias grep="grep --color=auto"
alias vi="vim"
alias vim="nvim"
alias r="antigen update"
alias tat='tmux new-session -As $(basename "$PWD" | tr . -)' # will attach if session exists, or create a new session
alias tmuxsrc="tmux source-file ~/.tmux.conf"
alias tmuxkillall="tmux ls | cut -d : -f 1 | xargs -I {} tmux kill-session -t {}" # tmux kill all sessions
alias ct="ctags -R --exclude=.git --exclude=node_modules"
alias dotfiles="ls -a | grep '^\.' | grep --invert-match '\.DS_Store\|\.$'"

# }}}

# Go {{{

export GOPATH=$HOME/Documents/Go
if [ -d $HOME/Documents/Go/bin ]; then
	PATH="$PATH:$HOME/Documents/Go/bin"
fi

# }}}

# Github {{{

export GITHUB_USER="1995parham"
export HOMEBREW_GITHUB_API_TOKEN="0dcb9b50e36d83de6ddbcff7b448b929399fc869"

# }}}

# proxy {{{

export parham_usvs="151.80.199.92"

function proxy_start() {
	dig +short myip.opendns.com @resolver1.opendns.com

	ssh -fTN -L 38080:127.0.0.1:38080 $parham_usvs

	export {http,https,ftp}_proxy=127.0.0.1:38080
	
	curl ipinfo.io/ip
}

function proxy_stop() {
	ps aux | grep "ssh -fTN" | grep "38080:" | awk '{print $2}' | xargs kill
	unset {http,https,ftp}_proxy
}

# }}}
