# Setup
title:       	  .Files
description:    My Personal Linux & OSX configurations files
paginate:       1
show_downloads: true

# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge


# Navigation
navigation:
- text: Home
  url: /dotfiles
- text: Home Sweet Home
  url: /dotfiles/home
- text: How to ...
  url: /dotfiles/how
- text: VIM
  url: /dotfiles/vim
- text: ZSH
  url : /dotfiles/zsh
