# Setup
title:       	  .Files
description:    My Personal Linux & OSX configurations files
paginate:       1
show_downloads: true

# Navigation
navigation:
- text: Home
  url: /dotfiles
- text: Home Servers
  url: /dotfiles/home
- text: How to ...
  url: /dotfiles/how
- text: VIM
  url: /dotfiles/vim
- text: ZSH
  url : /dotfiles/zsh
