# Setup
title:       	  .Files
description:    My Personal Linux & OSX configurations files
paginate:       1
show_downloads: true

# Navigation
navigation:
- text: Home
  url: /dotfiles
- text: Home Servers
  url: /dotfiles/home.md
- text: How to ...
  url: /dotfiles/how.md
- text: VIM
  url: /dotfiles/vim.md
- text: ZSH
  url : /dotfiles/zsh.md
